name: profile_peneliti
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_framework: ^1.5.1
  url_launcher: ^6.3.0
  provider: ^6.1.2
  universal_io: ^2.2.2
  google_fonts: ^5.1.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/
  #   - assets/fonts

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-ExtraLight.ttf
  #         weight: 200
  #       - asset: fonts/Inter-Light.ttf
  #         weight: 300
  #       - asset: fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Inter-ExtraBold.ttf
  #         weight: 800
  #       - asset: fonts/Inter-Black.ttf
  #         weight: 900
