allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

buildscript {
    repositories {
    google()
    mavenCentral()
  }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.3'
        
    }
}

rootProject.layout.buildDirectory = "../build"
subprojects {
    rootProject.layout.buildDirectory = "${rootProject.layout.buildDirectory}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
